/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/claim": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_claim_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a set of user credentials and returns an access and refresh JSON web
         *     token pair to prove the authentication of those credentials.
         */
        post: operations["auth_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * @description Takes a refresh type JSON web token and returns an access type JSON web
         *     token if the refresh token is valid.
         */
        post: operations["auth_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["auth_register_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["classes_cancel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{id}/checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Check-in con validación del backend (A10 / §6.3). */
        post: operations["classes_checkin_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/classes/{id}/reserve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Reservar (idempotente con client_id) o entrar a lista de espera. */
        post: operations["classes_reserve_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["devices_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["devices_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/athletes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Atletas del gym: SOLO capa de relación (decisión 3). Aislamiento por gym. */
        get: operations["gym_athletes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Crear/listar clases del gym (A10). */
        get: operations["gym_classes_list"];
        put?: never;
        /** @description Crear/listar clases del gym (A10). */
        post: operations["gym_classes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description KPIs operativos del gym (A11). Separa ingresos por tarjeta vs. manual. */
        get: operations["gym_dashboard_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Invita por teléfono y vincula el Athlete Passport existente cuando aplica. */
        post: operations["gym_invitations_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Bandeja del gym para resolver solicitudes e invitaciones. */
        get: operations["gym_join_requests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/join-requests/{rid}/decide": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Aprobar / rechazar / ofrecer prueba / pedir info (A4). */
        post: operations["gym_join_requests_decide_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gym_memberships_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/memberships/{mid}/assign-plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Asignar plan / cuota personalizada a una membresía (A3 / A5). */
        post: operations["gym_memberships_assign_plan_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/overdue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Morosidad (A9): atletas con pago vencido en ESTE gym. */
        get: operations["gym_overdue_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Historial de pagos del gym (tarjeta + manual) (A7/A11). */
        get: operations["gym_payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/payments/manual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Registrar pago manual efectivo/transferencia (A7). No genera comisión. */
        post: operations["gym_payments_manual_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gym_plans_list"];
        put?: never;
        post: operations["gym_plans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{gym_id}/retention/at-risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Atletas en riesgo de abandono (A12) — gancho comercial principal. */
        get: operations["gym_retention_at_risk_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gym/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Edición del perfil/configuración por un rol del gym o superadmin. */
        get: operations["gym_retrieve"];
        /** @description Edición del perfil/configuración por un rol del gym o superadmin. */
        put: operations["gym_update"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Edición del perfil/configuración por un rol del gym o superadmin. */
        patch: operations["gym_partial_update"];
        trace?: never;
    };
    "/api/v1/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Buscar gyms por nombre/ubicación/tipo (A1). */
        get: operations["gyms_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gym_id}/dropins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gyms_dropins_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gym_id}/dropins/{product}/purchase": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Compra de drop-in: genera pago + compra con QR (R2). */
        post: operations["gyms_dropins_purchase_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{gym_id}/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Atleta solicita unirse a un gym (A4 escenario A). */
        post: operations["gyms_join_requests_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gyms/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["gyms_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["me_partial_update"];
        trace?: never;
    };
    "/api/v1/me/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Próximas clases de los gyms del atleta (§7.4). */
        get: operations["me_classes_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Consentimiento granular del atleta (§7.2 / T4). */
        get: operations["me_consents_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** @description Consentimiento granular del atleta (§7.2 / T4). */
        patch: operations["me_consents_partial_update"];
        trace?: never;
    };
    "/api/v1/me/join-requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Tracking de solicitudes propias (§7.3). */
        get: operations["me_join_requests_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_memberships_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/passport": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_passport_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/payments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Historial propio del atleta. Nunca expone pagos de terceros. */
        get: operations["me_payments_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/prs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me_prs_list"];
        put?: never;
        post: operations["me_prs_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/platform/gyms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Alta de gym reservada al superadmin de plataforma. */
        post: operations["platform_gyms_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/fel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["webhooks_fel_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/webhooks/pagalo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Webhook de Pagalo (§7.6). Idempotente por gateway_reference; verifica firma. */
        post: operations["webhooks_pagalo_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `self_signup` - Auto-registro
         *     * `gym_invited` - Invitado por gimnasio
         * @enum {string}
         */
        AccountOriginEnum: "self_signup" | "gym_invited";
        AssignPlan: {
            /** Format: uuid */
            plan_id?: string;
            /** Format: decimal */
            custom_fee?: string | null;
        };
        Athlete: {
            /** Format: uuid */
            readonly id: string;
            first_name: string;
            last_name: string;
            /** Format: date */
            birth_date?: string | null;
            /** Format: uri */
            photo_url?: string;
            emergency_contact?: unknown;
            /** Format: uuid */
            readonly global_qr_token: string;
            sport_level?: string;
            goals?: string;
            readonly global_points: number;
            readonly profile_completeness: number;
        };
        /** @description Cuenta autenticada + perfil global. Sirve a app y panel interno. */
        AthleteMe: {
            /** Format: uuid */
            readonly id: string;
            phone: string;
            phone_verified?: boolean;
            /** Format: email */
            email?: string | null;
            email_verified?: boolean;
            account_origin?: components["schemas"]["AccountOriginEnum"];
            readonly roles: components["schemas"]["StaffRole"][];
            athlete?: components["schemas"]["Athlete"] | null;
        };
        AthletePR: {
            /** Format: uuid */
            readonly id: string;
            pr_type: string;
            value: string;
            /** Format: date-time */
            achieved_at: string;
            /** Format: uuid */
            readonly validated_by_coach: string | null;
            /** Format: uuid */
            readonly validated_at_gym: string | null;
            is_public?: boolean;
            /** Format: date-time */
            readonly created_at: string;
        };
        Checkin: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly gym_class: string;
            /** Format: uuid */
            readonly athlete: string;
            /** Format: uuid */
            readonly membership: string | null;
            readonly method: components["schemas"]["CheckinMethodEnum"];
            /** Format: date-time */
            readonly checked_in_at: string;
        };
        CheckinAction: {
            method?: components["schemas"]["CheckinActionMethodEnum"];
        };
        /**
         * @description * `athlete_qr` - athlete_qr
         *     * `class_qr` - class_qr
         *     * `manual` - manual
         *     * `reception` - reception
         * @enum {string}
         */
        CheckinActionMethodEnum: "athlete_qr" | "class_qr" | "manual" | "reception";
        /**
         * @description * `athlete_qr` - QR del atleta
         *     * `class_qr` - QR de la clase
         *     * `manual` - Validación manual del coach
         *     * `reception` - Recepción
         * @enum {string}
         */
        CheckinMethodEnum: "athlete_qr" | "class_qr" | "manual" | "reception";
        /** @description Reclamo de cuenta creada por un gym. Vincula el atleta existente; nunca duplica. */
        Claim: {
            phone: string;
            password: string;
        };
        ClassDemand: {
            class_type: string;
            reservas: number;
        };
        Consent: {
            /** Format: uuid */
            readonly id: string;
            channel_type: components["schemas"]["ConsentChannelTypeEnum"];
            granted?: boolean;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `ops` - Operativa
         *     * `community` - Comunidad
         *     * `biz` - Comercial
         *     * `retention` - Retención
         * @enum {string}
         */
        ConsentChannelTypeEnum: "ops" | "community" | "biz" | "retention";
        ConsentUpdateItem: {
            channel_type: components["schemas"]["ConsentUpdateItemChannelTypeEnum"];
            granted: boolean;
        };
        /**
         * @description * `community` - community
         *     * `biz` - biz
         *     * `retention` - retention
         * @enum {string}
         */
        ConsentUpdateItemChannelTypeEnum: "community" | "biz" | "retention";
        /**
         * @description * `approve` - approve
         *     * `reject` - reject
         *     * `offer_trial` - offer_trial
         *     * `request_info` - request_info
         * @enum {string}
         */
        DecisionEnum: "approve" | "reject" | "offer_trial" | "request_info";
        Device: {
            /** Format: uuid */
            readonly id: string;
            fcm_token: string;
            platform: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        DropinProduct: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            gym: string;
            type: components["schemas"]["TypeEnum"];
            /** Format: decimal */
            price: string;
            is_active?: boolean;
        };
        DropinPurchase: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            gym: string;
            /** Format: uuid */
            dropin_product: string;
            /** Format: uuid */
            readonly qr_token: string;
            /** Format: date-time */
            valid_from: string;
            /** Format: date-time */
            valid_to: string;
            /** Format: date-time */
            readonly used_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        DropinPurchaseRequest: {
            /** @default card */
            method: components["schemas"]["Method528Enum"];
        };
        /**
         * @description * `not_required` - No requiere
         *     * `pending` - Pendiente
         *     * `issued` - Emitida
         *     * `failed` - Fallida
         * @enum {string}
         */
        FelStatusEnum: "not_required" | "pending" | "issued" | "failed";
        FelWebhook: {
            /** Format: uuid */
            payment_id: string;
            fel_status?: string;
            fel_reference?: string;
            /** Format: uri */
            document_url?: string;
        };
        /**
         * @description * `pagalo` - Pagalo
         *     * `manual` - Manual
         * @enum {string}
         */
        GatewayEnum: "pagalo" | "manual";
        /** @description Edición por admin gym / superadmin (incluye config sensible). */
        GymAdmin: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug?: string;
            /** Format: uri */
            logo_url?: string;
            description?: string;
            location_text?: string;
            address?: string;
            /** Format: decimal */
            lat?: string | null;
            /** Format: decimal */
            lng?: string | null;
            contact?: unknown;
            business_hours?: unknown;
            class_types?: unknown;
            is_public?: boolean;
            saas_plan?: components["schemas"]["SaasPlanEnum"];
            /** Format: decimal */
            platform_commission_pct?: string;
            /** Format: decimal */
            fixed_fee?: string | null;
            fiscal_data?: unknown;
            payout_config?: unknown;
        };
        GymClass: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly gym: string;
            class_type: string;
            /** Format: uuid */
            coach?: string | null;
            /** Format: date-time */
            starts_at: string;
            /** Format: int64 */
            duration_min?: number;
            /** Format: int64 */
            capacity?: number;
            readonly reserved_count: number;
            readonly has_capacity: boolean;
            level?: string;
            /** Format: decimal */
            cost?: string;
            included_in_plan?: boolean;
            cancellation_policy?: unknown;
            status?: string;
        };
        GymDashboard: {
            atletas_activos: number;
            morosos: number;
            /** Format: decimal */
            ingresos_mes_tarjeta: string;
            /** Format: decimal */
            ingresos_mes_manual: string;
            proximos_vencimientos: number;
            clases_mas_demandadas: components["schemas"]["ClassDemand"][];
        };
        /** @description Alta de invitado deduplicada por teléfono (A4 escenario B/C). */
        GymInvitation: {
            phone: string;
            /** Format: email */
            email?: string;
            first_name: string;
            last_name: string;
            comment?: string;
        };
        /** @description Perfil público del gym (A1) visible para atletas. */
        GymPublic: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            slug?: string;
            /** Format: uri */
            logo_url?: string;
            description?: string;
            location_text?: string;
            address?: string;
            /** Format: decimal */
            lat?: string | null;
            /** Format: decimal */
            lng?: string | null;
            contact?: unknown;
            business_hours?: unknown;
            class_types?: unknown;
        };
        JoinRequest: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            athlete: string;
            readonly athlete_name: string;
            /** Format: uuid */
            gym: string;
            readonly gym_name: string;
            /** Format: uuid */
            membership?: string | null;
            level?: string;
            goal?: string;
            preferred_schedule?: string;
            wants_trial?: boolean;
            comment?: string;
            status?: components["schemas"]["Status0a1Enum"];
            /** Format: date-time */
            readonly created_at: string;
            readonly history: components["schemas"]["MembershipStatusHistory"][];
        };
        JoinRequestCreate: {
            level?: string;
            goal?: string;
            preferred_schedule?: string;
            wants_trial?: boolean;
            comment?: string;
        };
        JoinRequestDecision: {
            decision: components["schemas"]["DecisionEnum"];
            comment?: string;
        };
        /** @description Registrar pago manual con conciliación (A7). */
        ManualPayment: {
            /** Format: uuid */
            membership_id: string;
            /** Format: decimal */
            amount: string;
            method: components["schemas"]["ManualPaymentMethodEnum"];
            /** Format: uri */
            proof_url?: string;
            /** Format: uri */
            proof_file?: string;
            /** @default membership */
            concept: components["schemas"]["ManualPaymentConceptEnum"];
        };
        /**
         * @description * `membership` - membership
         *     * `drop_in` - drop_in
         *     * `special_class` - special_class
         * @enum {string}
         */
        ManualPaymentConceptEnum: "membership" | "drop_in" | "special_class";
        /**
         * @description * `cash` - cash
         *     * `bank_transfer` - bank_transfer
         * @enum {string}
         */
        ManualPaymentMethodEnum: "cash" | "bank_transfer";
        /**
         * @description Vista del panel del gym: capa de relación de ESTE gym (decisión 3).
         *
         *     NUNCA expone datos de la vida del atleta en otros gimnasios.
         */
        MembershipAdmin: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            athlete: string;
            readonly athlete_name: string;
            status?: components["schemas"]["Status0a1Enum"];
            /** Format: uuid */
            plan?: string | null;
            /**
             * Format: decimal
             * @description Cuota personalizada que sobreescribe el precio del plan SOLO en esta relación.
             */
            custom_fee?: string | null;
            /** Format: decimal */
            readonly effective_fee: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            renewal_date?: string | null;
            auto_renew?: boolean;
            payment_method_pref?: components["schemas"]["PaymentMethodPrefEnum"];
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            /** Format: decimal */
            discount?: string | null;
            internal_notes?: string;
            /** Format: int64 */
            community_points?: number;
        };
        /** @description Vista del propio atleta de su relación con un gym (§7.2). */
        MembershipSelf: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            gym: string;
            readonly gym_name: string;
            status?: components["schemas"]["Status0a1Enum"];
            /** Format: uuid */
            plan?: string | null;
            readonly plan_name: string;
            /** Format: decimal */
            readonly effective_fee: string;
            /** Format: date */
            start_date?: string | null;
            /** Format: date */
            renewal_date?: string | null;
            payment_status?: components["schemas"]["PaymentStatusEnum"];
            /** Format: int64 */
            community_points?: number;
        };
        MembershipStatusHistory: {
            from_status?: string;
            to_status: string;
            comment?: string;
            /** Format: date-time */
            readonly changed_at: string;
        };
        /**
         * @description * `card` - Tarjeta
         *     * `cash` - Efectivo
         *     * `bank_transfer` - Transferencia
         * @enum {string}
         */
        Method528Enum: "card" | "cash" | "bank_transfer";
        PagaloWebhook: {
            reference: string;
            status: string;
        };
        PaginatedAthletePRList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["AthletePR"][];
        };
        PaginatedDropinProductList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["DropinProduct"][];
        };
        PaginatedGymClassList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["GymClass"][];
        };
        PaginatedGymPublicList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["GymPublic"][];
        };
        PaginatedJoinRequestList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["JoinRequest"][];
        };
        PaginatedMembershipAdminList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["MembershipAdmin"][];
        };
        PaginatedMembershipSelfList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["MembershipSelf"][];
        };
        PaginatedPaymentList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Payment"][];
        };
        PaginatedPlanList: {
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cD00ODY%3D"
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?cursor=cj0xJnA9NDg3
             */
            previous?: string | null;
            results: components["schemas"]["Plan"][];
        };
        /** @description Pasaporte completo (§7.2). Solo lo ve el propio atleta. */
        Passport: {
            athlete: components["schemas"]["Athlete"];
            memberships: unknown[];
            prs: components["schemas"]["AthletePR"][];
            clubs?: unknown[];
            dropins: unknown[];
        };
        PatchedAthlete: {
            /** Format: uuid */
            readonly id?: string;
            first_name?: string;
            last_name?: string;
            /** Format: date */
            birth_date?: string | null;
            /** Format: uri */
            photo_url?: string;
            emergency_contact?: unknown;
            /** Format: uuid */
            readonly global_qr_token?: string;
            sport_level?: string;
            goals?: string;
            readonly global_points?: number;
            readonly profile_completeness?: number;
        };
        PatchedConsentUpdate: {
            consents?: components["schemas"]["ConsentUpdateItem"][];
        };
        /** @description Edición por admin gym / superadmin (incluye config sensible). */
        PatchedGymAdmin: {
            /** Format: uuid */
            readonly id?: string;
            name?: string;
            slug?: string;
            /** Format: uri */
            logo_url?: string;
            description?: string;
            location_text?: string;
            address?: string;
            /** Format: decimal */
            lat?: string | null;
            /** Format: decimal */
            lng?: string | null;
            contact?: unknown;
            business_hours?: unknown;
            class_types?: unknown;
            is_public?: boolean;
            saas_plan?: components["schemas"]["SaasPlanEnum"];
            /** Format: decimal */
            platform_commission_pct?: string;
            /** Format: decimal */
            fixed_fee?: string | null;
            fiscal_data?: unknown;
            payout_config?: unknown;
        };
        Payment: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            athlete: string;
            /** Format: uuid */
            gym: string;
            /** Format: uuid */
            membership?: string | null;
            concept?: components["schemas"]["PaymentConceptEnum"];
            /** Format: decimal */
            amount: string;
            currency?: string;
            method: components["schemas"]["Method528Enum"];
            status?: components["schemas"]["PaymentStatusEnum"];
            gateway: components["schemas"]["GatewayEnum"];
            gateway_reference?: string;
            /** Format: decimal */
            platform_commission?: string;
            split_applied?: boolean;
            /** Format: uri */
            proof_url?: string;
            /** Format: uri */
            proof_file?: string;
            fel_status?: components["schemas"]["FelStatusEnum"];
            fel_reference?: string;
            /** Format: date-time */
            paid_at?: string | null;
            /** Format: date-time */
            readonly created_at: string;
        };
        /**
         * @description * `membership` - Membresía
         *     * `drop_in` - Drop-in
         *     * `special_class` - Clase especial
         *     * `personal_training` - Personal training
         *     * `marketplace` - Marketplace
         * @enum {string}
         */
        PaymentConceptEnum: "membership" | "drop_in" | "special_class" | "personal_training" | "marketplace";
        /**
         * @description * `card` - Tarjeta
         *     * `cash` - Efectivo
         *     * `bank_transfer` - Transferencia
         * @enum {string}
         */
        PaymentMethodPrefEnum: "card" | "cash" | "bank_transfer";
        /**
         * @description * `up_to_date` - Al día
         *     * `due_soon` - Por vencer
         *     * `overdue` - Vencido
         * @enum {string}
         */
        PaymentStatusEnum: "up_to_date" | "due_soon" | "overdue";
        Plan: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            readonly gym: string;
            name: string;
            /** Format: decimal */
            price: string;
            /** Format: int64 */
            duration_days?: number;
            auto_renew_default?: boolean;
            /** Format: int64 */
            class_limit?: number | null;
            special_classes_access?: boolean;
            open_gym_access?: boolean;
            noshow_penalty?: unknown;
            /** Format: decimal */
            discount_allowed?: string | null;
            benefits?: unknown;
            is_active?: boolean;
        };
        /** @description Auto-registro: teléfono + contraseña. Crea el atleta (decisión 1). */
        Register: {
            phone: string;
            password: string;
            /** Format: email */
            email?: string;
            first_name: string;
            last_name: string;
        };
        Reservation: {
            /** Format: uuid */
            readonly id: string;
            /** Format: uuid */
            gym_class: string;
            /** Format: uuid */
            readonly athlete: string;
            readonly status: components["schemas"]["ReservationStatusEnum"];
            /** @description Idempotencia de acciones offline (T6). */
            client_id?: string;
            /** Format: date-time */
            readonly created_at: string;
        };
        ReservationAction: {
            client_id?: string;
        };
        /**
         * @description * `reserved` - Reservada
         *     * `waitlist` - Lista de espera
         *     * `cancelled` - Cancelada
         *     * `no_show` - No-show
         * @enum {string}
         */
        ReservationStatusEnum: "reserved" | "waitlist" | "cancelled" | "no_show";
        /**
         * @description * `starter` - Starter
         *     * `growth` - Growth
         *     * `pro` - Pro
         *     * `enterprise` - Enterprise
         * @enum {string}
         */
        SaasPlanEnum: "starter" | "growth" | "pro" | "enterprise";
        StaffRole: {
            role: string;
            /** Format: uuid */
            gym_id: string | null;
            /** Format: uuid */
            club_id: string | null;
        };
        /**
         * @description * `requested` - Solicitada
         *     * `invited` - Invitado
         *     * `pending_approval` - Pendiente de aprobación
         *     * `approved_no_plan` - Aprobada sin plan
         *     * `active` - Activa
         *     * `trial` - En prueba
         *     * `paused` - Pausada
         *     * `expired` - Vencida
         *     * `rejected` - Rechazada
         *     * `former_member` - Exmiembro
         *     * `blocked` - Bloqueada
         *     * `drop_in` - Drop-in
         * @enum {string}
         */
        Status0a1Enum: "requested" | "invited" | "pending_approval" | "approved_no_plan" | "active" | "trial" | "paused" | "expired" | "rejected" | "former_member" | "blocked" | "drop_in";
        TokenObtainPair: {
            phone: string;
            password: string;
            readonly access: string;
            readonly refresh: string;
        };
        TokenPair: {
            access: string;
            refresh: string;
        };
        TokenRefresh: {
            readonly access: string;
            refresh: string;
        };
        /**
         * @description * `one_class` - Una clase
         *     * `day` - Un día
         *     * `week` - Una semana
         *     * `open_gym` - Open gym
         *     * `special` - Clase especial
         *     * `free_trial` - Prueba gratuita
         * @enum {string}
         */
        TypeEnum: "one_class" | "day" | "week" | "open_gym" | "special" | "free_trial";
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_claim_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Claim"];
                "application/x-www-form-urlencoded": components["schemas"]["Claim"];
                "multipart/form-data": components["schemas"]["Claim"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    auth_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenObtainPair"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
                "multipart/form-data": components["schemas"]["TokenObtainPair"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenObtainPair"];
                };
            };
        };
    };
    auth_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefresh"];
                "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
                "multipart/form-data": components["schemas"]["TokenRefresh"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenRefresh"];
                };
            };
        };
    };
    auth_register_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Register"];
                "application/x-www-form-urlencoded": components["schemas"]["Register"];
                "multipart/form-data": components["schemas"]["Register"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
        };
    };
    classes_cancel_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    classes_checkin_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["CheckinAction"];
                "application/x-www-form-urlencoded": components["schemas"]["CheckinAction"];
                "multipart/form-data": components["schemas"]["CheckinAction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Checkin"];
                };
            };
        };
    };
    classes_reserve_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReservationAction"];
                "application/x-www-form-urlencoded": components["schemas"]["ReservationAction"];
                "multipart/form-data": components["schemas"]["ReservationAction"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Reservation"];
                };
            };
        };
    };
    devices_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Device"];
                "application/x-www-form-urlencoded": components["schemas"]["Device"];
                "multipart/form-data": components["schemas"]["Device"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    devices_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gym_athletes_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipAdminList"];
                };
            };
        };
    };
    gym_classes_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGymClassList"];
                };
            };
        };
    };
    gym_classes_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GymClass"];
                "application/x-www-form-urlencoded": components["schemas"]["GymClass"];
                "multipart/form-data": components["schemas"]["GymClass"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymClass"];
                };
            };
        };
    };
    gym_dashboard_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymDashboard"];
                };
            };
        };
    };
    gym_invitations_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GymInvitation"];
                "application/x-www-form-urlencoded": components["schemas"]["GymInvitation"];
                "multipart/form-data": components["schemas"]["GymInvitation"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequest"];
                };
            };
        };
    };
    gym_join_requests_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `requested` - Solicitada
                 *     * `invited` - Invitado
                 *     * `pending_approval` - Pendiente de aprobación
                 *     * `approved_no_plan` - Aprobada sin plan
                 *     * `active` - Activa
                 *     * `trial` - En prueba
                 *     * `paused` - Pausada
                 *     * `expired` - Vencida
                 *     * `rejected` - Rechazada
                 *     * `former_member` - Exmiembro
                 *     * `blocked` - Bloqueada
                 *     * `drop_in` - Drop-in
                 */
                status?: "active" | "approved_no_plan" | "blocked" | "drop_in" | "expired" | "former_member" | "invited" | "paused" | "pending_approval" | "rejected" | "requested" | "trial";
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJoinRequestList"];
                };
            };
        };
    };
    gym_join_requests_decide_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
                rid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JoinRequestDecision"];
                "application/x-www-form-urlencoded": components["schemas"]["JoinRequestDecision"];
                "multipart/form-data": components["schemas"]["JoinRequestDecision"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequest"];
                };
            };
        };
    };
    gym_memberships_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /**
                 * @description * `up_to_date` - Al día
                 *     * `due_soon` - Por vencer
                 *     * `overdue` - Vencido
                 */
                payment_status?: "due_soon" | "overdue" | "up_to_date";
                plan?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `requested` - Solicitada
                 *     * `invited` - Invitado
                 *     * `pending_approval` - Pendiente de aprobación
                 *     * `approved_no_plan` - Aprobada sin plan
                 *     * `active` - Activa
                 *     * `trial` - En prueba
                 *     * `paused` - Pausada
                 *     * `expired` - Vencida
                 *     * `rejected` - Rechazada
                 *     * `former_member` - Exmiembro
                 *     * `blocked` - Bloqueada
                 *     * `drop_in` - Drop-in
                 */
                status?: "active" | "approved_no_plan" | "blocked" | "drop_in" | "expired" | "former_member" | "invited" | "paused" | "pending_approval" | "rejected" | "requested" | "trial";
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipAdminList"];
                };
            };
        };
    };
    gym_memberships_assign_plan_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
                mid: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["AssignPlan"];
                "application/x-www-form-urlencoded": components["schemas"]["AssignPlan"];
                "multipart/form-data": components["schemas"]["AssignPlan"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MembershipAdmin"];
                };
            };
        };
    };
    gym_overdue_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipAdminList"];
                };
            };
        };
    };
    gym_payments_list: {
        parameters: {
            query?: {
                /**
                 * @description * `membership` - Membresía
                 *     * `drop_in` - Drop-in
                 *     * `special_class` - Clase especial
                 *     * `personal_training` - Personal training
                 *     * `marketplace` - Marketplace
                 */
                concept?: "drop_in" | "marketplace" | "membership" | "personal_training" | "special_class";
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `card` - Tarjeta
                 *     * `cash` - Efectivo
                 *     * `bank_transfer` - Transferencia
                 */
                method?: "bank_transfer" | "card" | "cash";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `pending` - Pendiente
                 *     * `succeeded` - Exitoso
                 *     * `failed` - Fallido
                 *     * `refunded` - Reembolsado
                 */
                status?: "failed" | "pending" | "refunded" | "succeeded";
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentList"];
                };
            };
        };
    };
    gym_payments_manual_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualPayment"];
                "application/x-www-form-urlencoded": components["schemas"]["ManualPayment"];
                "multipart/form-data": components["schemas"]["ManualPayment"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    gym_plans_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPlanList"];
                };
            };
        };
    };
    gym_plans_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Plan"];
                "application/x-www-form-urlencoded": components["schemas"]["Plan"];
                "multipart/form-data": components["schemas"]["Plan"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Plan"];
                };
            };
        };
    };
    gym_retention_at_risk_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipAdminList"];
                };
            };
        };
    };
    gym_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymAdmin"];
                };
            };
        };
    };
    gym_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GymAdmin"];
                "application/x-www-form-urlencoded": components["schemas"]["GymAdmin"];
                "multipart/form-data": components["schemas"]["GymAdmin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymAdmin"];
                };
            };
        };
    };
    gym_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedGymAdmin"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedGymAdmin"];
                "multipart/form-data": components["schemas"]["PatchedGymAdmin"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymAdmin"];
                };
            };
        };
    };
    gyms_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGymPublicList"];
                };
            };
        };
    };
    gyms_dropins_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedDropinProductList"];
                };
            };
        };
    };
    gyms_dropins_purchase_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
                product: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DropinPurchaseRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DropinPurchaseRequest"];
                "multipart/form-data": components["schemas"]["DropinPurchaseRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DropinPurchase"];
                };
            };
        };
    };
    gyms_join_requests_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                gym_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["JoinRequestCreate"];
                "application/x-www-form-urlencoded": components["schemas"]["JoinRequestCreate"];
                "multipart/form-data": components["schemas"]["JoinRequestCreate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JoinRequest"];
                };
            };
        };
    };
    gyms_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymPublic"];
                };
            };
        };
    };
    me_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AthleteMe"];
                };
            };
        };
    };
    me_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAthlete"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAthlete"];
                "multipart/form-data": components["schemas"]["PatchedAthlete"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Athlete"];
                };
            };
        };
    };
    me_classes_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedGymClassList"];
                };
            };
        };
    };
    me_consents_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"][];
                };
            };
        };
    };
    me_consents_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedConsentUpdate"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedConsentUpdate"];
                "multipart/form-data": components["schemas"]["PatchedConsentUpdate"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"][];
                };
            };
        };
    };
    me_join_requests_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJoinRequestList"];
                };
            };
        };
    };
    me_memberships_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedMembershipSelfList"];
                };
            };
        };
    };
    me_passport_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Passport"];
                };
            };
        };
    };
    me_payments_list: {
        parameters: {
            query?: {
                /**
                 * @description * `membership` - Membresía
                 *     * `drop_in` - Drop-in
                 *     * `special_class` - Clase especial
                 *     * `personal_training` - Personal training
                 *     * `marketplace` - Marketplace
                 */
                concept?: "drop_in" | "marketplace" | "membership" | "personal_training" | "special_class";
                /** @description The pagination cursor value. */
                cursor?: string;
                /**
                 * @description * `card` - Tarjeta
                 *     * `cash` - Efectivo
                 *     * `bank_transfer` - Transferencia
                 */
                method?: "bank_transfer" | "card" | "cash";
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
                /**
                 * @description * `pending` - Pendiente
                 *     * `succeeded` - Exitoso
                 *     * `failed` - Fallido
                 *     * `refunded` - Reembolsado
                 */
                status?: "failed" | "pending" | "refunded" | "succeeded";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentList"];
                };
            };
        };
    };
    me_prs_list: {
        parameters: {
            query?: {
                /** @description The pagination cursor value. */
                cursor?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAthletePRList"];
                };
            };
        };
    };
    me_prs_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AthletePR"];
                "application/x-www-form-urlencoded": components["schemas"]["AthletePR"];
                "multipart/form-data": components["schemas"]["AthletePR"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AthletePR"];
                };
            };
        };
    };
    platform_gyms_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GymAdmin"];
                "application/x-www-form-urlencoded": components["schemas"]["GymAdmin"];
                "multipart/form-data": components["schemas"]["GymAdmin"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GymAdmin"];
                };
            };
        };
    };
    webhooks_fel_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FelWebhook"];
                "application/x-www-form-urlencoded": components["schemas"]["FelWebhook"];
                "multipart/form-data": components["schemas"]["FelWebhook"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    webhooks_pagalo_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PagaloWebhook"];
                "application/x-www-form-urlencoded": components["schemas"]["PagaloWebhook"];
                "multipart/form-data": components["schemas"]["PagaloWebhook"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
